spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hwe?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate   # let Flyway own the schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.time_zone: UTC
        format_sql: true
    open-in-view: false     # push DB work to service layer transactions
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true   # handy if connecting to a non-empty schema
    validate-migration-naming: true
