-- Basic table setup
CREATE TABLE IF NOT EXISTS player (
  id            BIGINT AUTO_INCREMENT PRIMARY KEY,
  display_name  VARCHAR(64) NOT NULL UNIQUE,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_dt    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_dt    TIMESTAMP DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS tile (
  id            BIGINT AUTO_INCREMENT PRIMARY KEY,
  title         VARCHAR(128) NOT NULL,
  description   TEXT NOT NULL,
  weight        INT NOT NULL,
  icon_path     TEXT NOT NULL,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_dt    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_dt    TIMESTAMP DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
